name: vakinha_burger_api
description: Vakinha Burguer API.
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  args: ^2.0.0
  dio: ^4.0.0
  dio_http2_adapter: ^2.0.0
  dotenv: ^3.0.0
  mysql1: ^0.19.2
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.4
  http: ^0.13.0
  lints: ^1.0.0
  shelf_router_generator: ^1.0.1
  test: ^1.15.0
  test_process: ^2.0.0
